erp42_control:
#Input Torque
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  left_front_wheel_controller:
    type: "effort_controllers/JointEffortController"
    joint: left_front_wheel_joint
    pid: {p: 1.0, i: 0, d: 0}

  left_back_wheel_controller:
    type: "effort_controllers/JointEffortController"
    joint: left_back_wheel_joint 
    pid: {p: 1.0, i: 0, d: 0}

  right_front_wheel_controller:
    type: "effort_controllers/JointEffortController"
    joint: right_front_wheel_joint
    pid: {p: 1.0, i: 0, d: 0}

  right_back_wheel_controller:
    type: "effort_controllers/JointEffortController"
    joint: right_back_wheel_joint
    pid: {p: 1, i: 0, d: 0}

  right_steer_wheel_controller:
    type: "position_controllers/JointPositionController"
    joint: right_front_disk_wheel_joint
    #pid: {p: 500.0, i: 0, d: 0.1}

  left_steer_wheel_controller:
    type: "position_controllers/JointPositionController"
    joint: left_front_disk_wheel_joint
    #pid: {p: 500.0, i: 0, d: 0.1}
    #"effort_controllers/JointPositionController"

#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

#http://gazebosim.org/tutorials/?tut=ros_control (use RQT for PID Tune)
#https://www.youtube.com/watch?v=gA-O39LrXzI (PID Tune) start 4.5 minute
#https://github.com/amin-amani/gazebo_plugin_tutorials/wiki/03.-Transfer-and-control-joints--with-ros (type of controllers)
# http://wiki.ros.org/ros_control#Controllers 
 

